name: procguard
version: '1.2'
summary: Bash process watchdog for Betterstack alerts
description: |
  Bash process watchdog for Betterstack alerts

grade: stable
confinement: classic
base: core24

apps:
  procguard:
    command: bin/procguard-watchdog.sh

parts:
  procguard:
    plugin: dump
    source: .
    organize:
      bin/procguard-watchdog.sh: bin/procguard-watchdog.sh

