name: Build Brew Formula

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and install procguard
        run: |
          brew tap goodylabs/betterstack-procguard https://github.com/goodylabs/betterstack-procguard
          brew install procguard
          procguard --help